dataset:
    data_path: ./data/okvqa
    dataset_name: OKVQA
    split: test
    testing: False
    max_samples: 30
    batch_size: 2
    start_sample: 0

prompt: ./prompts/benchmarks/okvqa.prompt

results_dir: ./results/okvqa/all/

load_models:
    maskrcnn: False
    clip: False
    glip: False
    owlvit: False
    tcl: False
    gpt3_list: True # Ez dakit noiz erabiltzen den
    gpt3_qa: True
    gpt3_guess: True
    depth: False
    blip: True
    saliency: False
    xvlm: False

fixed_code_file: ./prompts/fixed_code/blip2.prompt
