dataset:
    data_path: ./data/okvqa
    dataset_name: OKVQA
    split: test
    testing: False
    max_samples: 4
    batch_size: 1 # to test set 1
    start_sample: 0
codex:
    prompt: ./prompts/benchmarks/okvqa.prompt

results_dir: ./results/okvqa/all/

load_models:
    maskrcnn: False
    clip: False
    glip: False
    owlvit: False
    tcl: False
    # gpt3_list: True 
    qa: True
    guess: True
    depth: False
    blip: True
    saliency: False
    xvlm: False
    

save: True
save_codex: False
execute_code: True
use_cached_codex: False

fixed_code_file: ./prompts/fixed_code/blip2.prompt

