dataset:
    data_path: './data/gqa'
    dataset_name: GQA
    split: testdev
    testing: False
    max_samples: 1
    batch_size: 1
    start_sample: 0

prompt : ./prompts/benchmarks/gqa.prompt
results_dir : ./results/gqa/

load_models:
    maskrcnn: True
    clip: False
    glip: True
    owlvit: False
    tcl: False
    gpt3_list: False
    gpt3_qa: False
    gpt3_guess: False
    depth: False
    blip: True
    saliency: False
    xvlm: True
    codellama_Q: True

fixed_code_file: ./prompts/fixed_code/blip2.prompt