dataset:
  data_path: ./data/refcoco
  dataset_name: RefCOCO
  split_by: unc  # [google, unc]
  split: testA
  version: refcoco+
  batch_size: 5 # set to number 3 
  max_samples:

codex:
  prompt: ./prompts/benchmarks/refcoco.prompt

results_dir: ./results/refcoco/all/

load_models:
  gpt3_general: False

save: True
save_codex: False
use_cached_codex: False
execute_code: True

fixed_code_file: ./prompts/fixed_code/glip.prompt


